#!/usr/bin/env bash
# Compare the fat and slim images using slim xray reports.
# Run from this directory after fat.report.json and slim.report.json
# have been generated by `slim xray` (see the article).

set -euo pipefail

# 1. Compare Dockerfile-style build instructions per layer.
echo "=== Build instructions: fat vs slim ==="
diff \
  <(jq -S '.image_layers[].change_instruction.all' fat.report.json) \
  <(jq -S '.image_layers[].change_instruction.all' slim.report.json) \
  || true

# 2. Compare the top 20 largest files in each image.
jq '[.image_layers[].top[] | {name, size_human}]' fat.report.json  > fat.top.json
jq '[.image_layers[].top[] | {name, size_human}]' slim.report.json > slim.top.json

echo
echo "=== Top files: fat vs slim ==="
diff fat.top.json slim.top.json || true
